### PR TITLE
Update PortoutModel.php

### PR DESCRIPTION
**Pull request by tm1000**
Add missing fields to PortOuts

### CODE REVIEW

**Comment by ajrice6713** [comment]
Hey Andrew,

Thanks for this contribution! Let me check with the dev on our team who built our deploy pipeline before merging this, we are modifying the process and I want to make sure this will deploy successfully. 

He is back next week after New Years

**Comment by tm1000** [comment]
@ajrice6713 Hey AJ! 

We've actually talked a couple of times over support. Anyways everything you've said is all good. I've already extended the class to add what I wanted for now, which leads me to my next quick question if you have the time. Why are all classes in this API final, for my 'extend' I simply just recreated the file but if I could extend it it would have been much easier.

**Comment by ajrice6713** [comment]
@tm1000 Hey Andrew! 

Great question on the final classes - this is an older SDK that was written by someone who doesn't work at Bandwidth anymore - so as for the 'why' they are all final classes, I couldn't tell you. 

We are working on a new IRIS SDK that will be auto generated from our OpenAPI spec, we are closing in on the final stages and hope to have something released in Q1. This new SDK shouldn't utilize final classes, and when the team at bandwidth that manages the IRIS API publishes a new spec with any changed fields, the SDK will be automatically updated to match when they publish their updated API spec - hopefully resolving issues like this one in the future.

**Comment by tm1000** [comment]
Thanks for the explanation AJ! Looking forward to the updates coming up!

**Pull request merged**
